[package]
name = "internal_dsl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies] # <-- We added this and everything after!

[dependencies]
rand = "0.8"
itertools = "0.13.0"


